### ISSUE TITLE
package.json version

### ISSUE THREAD

**Issue by codemonkey00** [toverux/ngsweetalert2#1]
When I put "ngsweetalert2" into my package.json it tells me unavailable for the version. 
If I try to get packages with no version number i get this error:
    npm ERR! 404  'ngsweetalert2' is not in the npm registry.

**Comment by toverux** [comment]
Hi, that's normal, ngsweetalert is a scoped package (scoped to my username).

You have to run this : `npm install --save @toverux/ngsweetalert2` (notice the @toverux/ prefix).

Read more here : https://docs.npmjs.com/misc/scope
Name collisions are too frequent in npm's ecosystem, and I think that much more people should scope their package names.

**Comment by codemonkey00** [comment]
Thanks a ton.  That worked.  I did have to update from angular 2.2 to 2.4, but once I did that it downloaded.  I look forward to trying this since the other sweet alert packages are no longer updated.
