### ISSUE TITLE
Can this using sweetalert2 methods with ngsweetalert2?

### ISSUE THREAD

**Issue by taipeiwu** [toverux/ngsweetalert2#11]
If I will trigger an event,
through the component's code to trigger the closure of the window,
I need to use the close method ( swal.close() ).

**Comment by toverux** [comment]
Hi @taipeiwu,

You can still use SweetAlert's methods directly by requiring the library.

```typescript
import swal from 'sweealert2';

// ...
swal.close();
```

(Note that SweetAlert2 already has types definition embedded in it, so no need to install them separately.)
