### ISSUE TITLE
Error handling with show().then() 

### ISSUE THREAD

**Issue by ChinesePeanuts** [toverux/ngsweetalert2#13]
Hi,

I would like to achieve a simple deletion confirmation swal.

So for the moment I have a `<swal></swal>` as followed : 
```
<swal #dialog title="Delete?" type="warning" (confirm)="onDelete(item)"></swal>
<swal #dialogsuccess title="Deleted!" type="success"></swal>
<swal #dialogerror title="Error!" text="An error has been raised" type="error"></swal>
<button md-button class="action-buttons" mdTooltip="Delete" mdTooltipPosition="right" (click)="dialog.show().then(dialogsuccess.show)"></button>
```
The `onDelete()` function returns a Promise but I don't really know how to handle errors in the `dialog.show().then` right now, even if the Promise returns an error, I can't handle it with a proper swal

I can't really do the same as in VanillaJS

Thanks in advance

**Comment by toverux** [comment]
Hi @ChinesePeanuts,

I think that you want this:

```html
<swal #dialog title="Delete?" type="warning" (confirm)="onDelete(item).on(dialogsuccess.show, dialogerror.show)"></swal>
<swal #dialogsuccess title="Deleted!" type="success"></swal>
<swal #dialogerror title="Error!" text="An error has been raised" type="error"></swal>
<button md-button class="action-buttons" mdTooltip="Delete" mdTooltipPosition="right" (click)="dialog.show()"></button>
```

Remember that show() returns a Promise that juste tells whether Ok or Cancel have been pressed. Not the success of some other operation... Displaying #dialogsuccess or #dialogerror must be done at #dialog's level ;)
