### ISSUE TITLE
cancel/dismiss button markup getting set to display: none;

### ISSUE THREAD

**Issue by vegaskev** [toverux/ngsweetalert2#14]
For some reason when using the `[swal]` attribute in a `<button>` element, `(cancel)` generates the button markup for it properly, however for some reason it is set to `display: none;`.  

I have tried placing cancel before confirm like this...

`
        <button [swal]="['Delete?', 'This cannot be undone.', 'warning']" (cancel)="cancelTest()" (confirm)="confirmTest()">
          Test Sweet Alert
        </button>
`

and I've tried it with cancel after the confirm like this...

`
        <button [swal]="['Delete?', 'This cannot be undone.', 'warning']" (confirm)="confirmTest()" (cancel)="cancelTest()">
          Test Sweet Alert
        </button>
`

Thanks in advance.

### Update:
- I should note that my confirmTest() is being triggered when the 'ok' button is selected by user.
#### Did another test or two...
- I also just tried to create a sweet alert with no confirm method and just a cancel method.  When I did this, it created an 'ok' button in the dialog, however it didn't call my (cancel) method, it just fired off into nothingness.  I would imagine sweet alert automatically creates an confirm method and 'ok' button no matter what....idk.  During this test when I viewed the markup, both the confirm and cancel button markup appeared, however once again the 'cancel' button's button element was set to display: none;

**Comment by toverux** [comment]
Hi @vegaskev, that's normal, by default Swal2 has no cancel button, because it's simple alert()-like modals. So the user can just say "Ok".
Setting `(cancel)` has no influence on this, but you can also trigger it by clicking on the page overlay given that `allowOutsideClick` is enabled.

In your case you need to enable `showCancelButton` in the options.

So your markup will look like this:

```html
<button [swal]="{ title: 'Delete?', text: 'This cannot be undone.', type: 'warning', showCancelButton: true }" (confirm)="confirmHandler()" (cancel)="cancelHandler()">
```
