### ISSUE TITLE
How to implement a counter

### ISSUE THREAD

**Issue by santoshkt** [toverux/ngsweetalert2#15]
I am using ng-idle to implement a session timeout counter. What is the best way to update the swal dialog text ? Right now, I am calling show multiple times in the subscribe of count down timer change but that is throwing alert multiple times instead of just updating the time value. It worked earlier today without throwing multiple alerts but I am not sure what I changed but it stopped working correctly.

**Comment by toverux** [comment]
Hi @santoshkt, sorry for the delay. Is your problem solved?

That should work indeed... SweetAlert2 doesn't support displaying multiple alerts at the same time, I don't see how it could display multiple modals...

Anyway, you can access the currently-displayed-alert's content via `swal.getContent()` (https://github.com/limonte/sweetalert2#methods), that will return a DOM element, that you can modify.
