### ISSUE TITLE
Translation in sweetalert

### ISSUE THREAD

**Issue by lippomano** [toverux/ngsweetalert2#17]
Is it possible to ha a sweetalert localized?
In my angular application I am using ngx-translate and in my html I have something like this:
`{{user.validations.invalid | translate}}`

If it's not possible is there a way to have a translation in my sweetalert?

**Comment by toverux** [comment]
Hi @lippomano,

I'm also a user of ngx-translate. You can obviously use the pipe it provides in ngsweetalert's component and directive!

```html
<swal [title]="'my_title_id'|translate"></swal>

<button [swal]="['my_title_id'|translate, 'my_message_id'|translate]"></button>
```

**Comment by lGomaal** [comment]
Hi @toverux ,

I used your approach for translating but it didn't work , but when i used the @aceleghin approach worked just fine with the "title" attribute , now my problem is that when i used both ways to translate "text" attribute , it doesn't work at all as it not even rendering "div" or any tag for my text and show nothing,  examples down here :

**this is  what my swal component looks like**
`<swal #otpSwal text="{{'CARD_MANAGEMENT.OTP_CODE_MSG'|translate}}" icon="info" [allowOutsideClick]="false"
        (confirm)='validateOtp()'> </swal>`

**i included the swal module both on the app module and the child module as will like so** 

`import { SweetAlert2Module } from '@sweetalert2/ngx-sweetalert2';
  imports: [
    SweetAlert2Module
  ],`

**here is what my swal looks like**
![swalerror](https://user-images.githubusercontent.com/48729297/123613440-b5b56e80-d803-11eb-964b-e4d859fe6719.PNG)

What iam asking is can anyone just tell me what iam doing wrong here or even guide me to a documentation if existed to know the proper way to translate it , i searched alot without a solution for my problem.
