### ISSUE TITLE
Issue with alert closing

### ISSUE THREAD

**Issue by danilomcb** [toverux/ngsweetalert2#2]
Hi... I'm having trouble using sweetAlert. When it is closed, swal2-container blocks the other components of the screen.

**Comment by toverux** [comment]
Hello,

ngsweetalert2 is just an integration for [SweetAlert2](https://github.com/limonte/sweetalert2), we do not perform any DOM operations in this library, that's only "wrapping logic".

There may be a bug in the upstream library. Please open an issue in their repository, mentioning the browser you are using, and providing a jsfiddle to reproduce the bug.

**Comment by danilomcb** [comment]
I understand. Strangely it works by using  [SweetAlert.](https://github.com/limonte/sweetalert2) What happens is that when using ngsweetalert, the swal2-container created is not removed when closing the alert.

I'm going to adapt Sweetalert to my project. Thank you.

**Comment by toverux** [comment]
Oh, then it changes everything. Maybe your setup was incomplete, but I can't really find an explanation for such a bug. NgSweetalert2 calls sweetalert2 directly and does not perform any other DOM operation.

If you could provide the minimal boilerplate for reproducing the bug, I would be happy to investigate further, and I'll reopen the issue.

**Comment by gamunu** [comment]
I'm also having this issue, maybe because I'm using flexbox heavily (bootstrap v4). I tried including limonte/sweetalert2 scss styles to my project, doesn't seems to solve the problem.
