### ISSUE TITLE
Any plan to release npm pacakge instead of yarn?

### ISSUE THREAD

**Issue by kurotsukikaitou** [toverux/ngsweetalert2#21]

**Comment by limonte** [comment]
@toverux probably you need to change `yarn add` to `npm install` in the README. A lot of people, especially outside the JS community getting confused with `yarn`. 

For those who using yarn (like me) `npm install` will be more than  clear.

**Comment by toverux** [comment]
Done ! That's right, thanks @limonte, you're still more careful than me concerning DX / beginners :)
I thught that the mention of "npm registry" and thje npm badge were clear enough.

@kurotsukikaitou So, as you can understand, NgSweetalert2 already is on npm (yarn is an alternative client to the npm registry, that is, the server that hosts the packages) :)

**Comment by kurotsukikaitou** [comment]
I see. I'm a bit new of this node thing. Coming from Objective-C & Swift with multiple (3rd party, with no 1st party support) of package manager is kinda confusing :)

**Comment by cassianomon** [comment]
release npm pancake 😂
