### ISSUE TITLE
How to import SweetAlert's CSS file

### ISSUE THREAD

**Issue by shayts** [toverux/ngsweetalert2#22]
I can't find the SweetAlert's CSS file link.
How and where from,  can I import the css?

**Comment by toverux** [comment]
Hi @shayts, 

It's in `node_modules/sweetalert2/dist/sweetalert2.css`. The way you should import it then is up to you and depends on your configuration.

If you're using Angular CLI to build your app, there are two canonical ways to import vendor CSS files : https://stackoverflow.com/a/39152176/1724914

You can also import the SCSS file (`node_modules/sweetalert2/src/sweetalert2.scss`) if you're using SASS (and for example customize the variables that SweetAlert defines).

**Comment by shayts** [comment]
Thanks.
It works :)
