### ISSUE TITLE
Duplicate identifier

### ISSUE THREAD

**Issue by eloyleonardo** [toverux/ngsweetalert2#23]
I'm using with angular4 and when i try to add the module to the project the angular cli give me the duplicate error (below).  I added the css file, to the angular-cli config file, imported the module to the project and when i need to use in typescript i import the sweetalert2 directly.

Looks like this error is caused by my manual import of sweetalert2 and the module. But that's the recommendation. What can i do in this case ? 

the error: 
```
ERROR in ...../node_modules/sweetalert2/sweetalert2.d.ts (203,17): Duplicate identifier 'SweetAlertType'.
ERROR in ...../node_modules/sweetalert2/sweetalert2.d.ts (205,17): Duplicate identifier 'SweetAlertInputType'.
ERROR in ...../node_modules/sweetalert2/sweetalert2.d.ts (207,17): Duplicate identifier 'SweetAlertInputOptions'.
ERROR in ...../node_modules/sweetalert2/sweetalert2.d.ts (209,17): Duplicate identifier 'SweetAlertInputAttributes'.
ERROR in ...../node_modules/sweetalert2/sweetalert2.d.ts (614,5): Duplicate identifier 'default'.
ERROR in ...../node_modules/@toverux/ngsweetalert2/node_modules/sweetalert2/sweetalert2.d.ts (203,17): Duplicate identifier 'SweetAlertType'.
ERROR in ...../node_modules/@toverux/ngsweetalert2/node_modules/sweetalert2/sweetalert2.d.ts (205,17): Duplicate identifier 'SweetAlertInputType'.
ERROR in ...../node_modules/@toverux/ngsweetalert2/node_modules/sweetalert2/sweetalert2.d.ts (207,17): Duplicate identifier 'SweetAlertInputOptions'.
ERROR in ...../node_modules/@toverux/ngsweetalert2/node_modules/sweetalert2/sweetalert2.d.ts (209,17): Duplicate identifier 'SweetAlertInputAttributes'.
ERROR in ...../node_modules/@toverux/ngsweetalert2/node_modules/sweetalert2/sweetalert2.d.ts (614,5): Duplicate identifier 'default'.
```

my root module: 

```
import {SweetAlert2Module} from '@toverux/ngsweetalert2';

imports: [
   SweetAlert2Module.forRoot()
]
```

my ts file:

```
import {TranslateService} from 'ng2-translate';

constructor() {
   swal('foo');
  }

```

EDIT: Format

**Comment by toverux** [comment]
Hi @eloyleonardo,

I think you have installed sweetalert2 as a direct dependency (ie. it's written down in your package.json). However, it's also a dependency of ngsweetalert2. It installs it for you.
If you install it as a direct dependency you may end up with two sweetalert2 directories (that's your case here), the one installed by ngsweetalert2 and yours - that causes the duplicate identifier problem.

You can uninstall it (remove it from you direct deps) to fix the problem. You can still do `import swal from 'sweetalert2'` after that.

I'm considering changing that, so sweetalert2 would be a peer dependency of ngsweetalert2. But that's a breaking change so I won't do this until a next major.

**Comment by eloyleonardo** [comment]
Hi @toverux thankyou for your answer.
I remove the sweetalert from package.json, and now i can import the module. On the other hand i cant import the sweetalert2 module anymore. When i use `import swal from 'sweetalert2'` the angular cli give me an error: 
```
ERROR in ./src/app/services/my.service.ts
Module not found: Error: Can't resolve 'sweetalert2' in '../src/app/services/myservice'
resolve 'sweetalert2' in 'src/app/services/myservice'
  Parsed request is a module
  using description file: ../package.json 
```

How can i avoid this error and make the input works ? 
Thankyou again

**Comment by toverux** [comment]
You've done only part of the process :)

Remove your node_modules folder, and rerun `npm install`. Should be good then, since the dependency tree will be flattened, and sweetalert2 will be located at the top level in `node_modules/sweetalert2` instead of `node_modules/@toverux/ngsweetalert2/node_modules/sweetalert2`.

**Comment by julio899** [comment]
i can solvent using 
`npm i node-sass -D`
