### ISSUE TITLE
Consider making the Plunker template and adding CONTRIBUTING.md

### ISSUE THREAD

**Issue by limonte** [toverux/ngsweetalert2#25]
Something like https://github.com/limonte/sweetalert2/blob/master/.github/CONTRIBUTING.md would be good-to-have in order to encourage bug-reporters to put some effort in making questions.

**Comment by toverux** [comment]
Say welcome to [CONTRIBUTING.md](https://github.com/toverux/ngsweetalert2/blob/master/CONTRIBUTING.md)! o/

**Comment by limonte** [comment]
Yay! This is a very productive Saturday!

![](https://media.giphy.com/media/mWrXc8R1CJQxq/giphy.gif)
