### ISSUE TITLE
The right way to use it in Angular 2+

### ISSUE THREAD

**Issue by cassianomon** [toverux/ngsweetalert2#27]
Hello, is this the right way to use?

    <swal #foo title="Confirma liquidação?"
        [options]="{
            confirmButtonText: 'Liquidar',
            confirmButtonClass: 'btn btn-xs btn-success',
            cancelButtonClass: 'btn btn-xs btn-danger',
            cancelButtonText: 'Cancelar',
            showCancelButton: true
        }"
        (confirm)="confirmar()"
        (cancel)="cancelar()">
    </swal>
    <button type="button"
        (click)="foo.show()"
        class="btn btn-xs btn-success">
        Liquidar
    </button>

Also I would need to change the directive name to something like <d-swal> and [d-swal] because of the name patterns we use, is there a way to do it?

**Comment by toverux** [comment]
Hi @cassianomon,

Yes, that's a legit use of the library, haha :smile: More seriously, yes, this is a normal, intended use of it.

Pro-tip: don't forget that you can set app-wide defaults for you swals, with `NgSweetAlert2Module.forRoot()`, ie.:

```typescript
@NgModule({
    imports: [
        SweetAlert2Module.forRoot({
            confirmButtonText: 'Liquidar',
            confirmButtonClass: 'btn btn-xs btn-success',
            cancelButtonClass: 'btn btn-xs btn-danger',
        })
    ]
})
```

That way, every Swal created will inherit of these options, avoiding inelegant duplications at template-level. You can still override these defaults when declaring a swal, though.

Your code will then be:

```html
<swal #foo 
    title="Confirma liquidação?"
    [options]="{ confirmButtonText: 'Liquidar', showCancelButton: true }"
    (confirm)="confirmar()" (cancel)="cancelar()">
</swal>
```

More generally: the goal of this library is to provide Angular utils to reduce the boilerplate, clutter and nesting in the TypeScript part of the component, so you can focus on the business logic in the .ts, and put more presentational things in the template.
See it as a declarative approach over an imperative one.

> Also I would need to change the directive name to something like and [d-swal] because of the name patterns we use, is there a way to do it?

None that I know, unfortunately. It can't even be a param or something like that: it must be declared statically in the library.

**Comment by cassianomon** [comment]
Thanks for the answer!!

Also, as you said, that it's a good practice to use a prefix in the app to diff from third-party libraries, we use prefixed directives and components that we create starting with <cdm-></cdm-> to differentiate from third-party and html tags. Would be this what you meant? Example:

```
<cdm-input-wrapper
    class="pull-left"
    innerStyle="margin: 0; padding: 0">
    <input type="text"
        class="text-right width140"
        id="numeroIdentificacao_{{ item.indexNames }}"
        name="numeroIdentificacao_{{ item.indexNames }}"
        [(ngModel)]="item.numeroIdentificacao"
        #numeroIdentificacao="ngModel"
        (paste)="pasteNumeroIdentificacao(i, $event)"
        (change)="numeroIdentificacaoUnidadeChange(item)"
        required>
</cdm-input-wrapper>
```

**Comment by toverux** [comment]
Are you talking about the `cdm-` prefix? Yes.
If your app is named _My Awesome App_ and has _MAA_ as initials, a component will be typically named `<maa-component>`, a pipe `| maaPipe`, and a directive `[maaDirective]`.

If we're good, I let you close the issue (we're leaving the original scope of it) :)

**Comment by cassianomon** [comment]
Haha, well, thanks.
