### ISSUE TITLE
Use directly from component or service?

### ISSUE THREAD

**Issue by avril-verhaeghen** [toverux/ngsweetalert2#33]
Hi,

I'm asking myself the question if it's possible to show the dialog directly from a component? Meaning I don't have a visual action that will trigger the `show` functionality.

For the moment I have to call another service and when this service resolves I will show an alert saying it's okay.

Tried to call functions directly from my component, but it doesn't work because of type issue and can't figure how exactly:

`import * as swal from 'sweetalert2';`
```
this.myService().subscribe((res) => {
      swal('Keep things simple :)');
      swal('The Internet?', 'That thing is still around?', 'question');
    });
```

**Comment by avril-verhaeghen** [comment]
Nevermind, found it, I was importing swal like this: `import * as swal from 'sweetalert2';` changed it to: `import swal from 'sweetalert2';`

**Comment by toverux** [comment]
Yep, SweetAlert has a `default` export :)

By the way, you can also declare the modal in the template (in the case you'd like to reuse the modal from the template or to separate concerns more) and use this:

```ts
class MyComponent {
    @ViewChild('swalDialog') private swalDialog: SwalComponent;

    public somewhere(): void {
        this.swalDialog.show();
    }
}
```
