### ISSUE TITLE
Use from a service

### ISSUE THREAD

**Issue by netopolit** [toverux/ngsweetalert2#4]
Is it possible to use it from a service? Something like:
```
sweetAlert.swal({
      title: 'Confirmation',
      text: 'Text.',
      type: 'question',
      showCancelButton: true,
      confirmButtonText: 'Yes',
      cancelButtonText: 'Cancel',
    })
```

Thank you

**Comment by toverux** [comment]
Hello,

Although it was originally planned, I don't really see the interest of this, since you can just:

```
swal({ title: 'Keep things simple :)' });
```

I'm not saying that a service is bad, but the amount of complexity it adds does not seem worthy.

However, if you can provide a real use case for that I'd be happy to implement such a thing!

**Comment by netopolit** [comment]
Hi,
Importing swal directly didn't cross my mind :). That will do the trick. Thanks!

**Comment by slzr** [comment]
I tried  `swal({ title: 'Keep things simple :)' });` but I gets error `cannot find name`, I missing something?

**Comment by toverux** [comment]
Hi @slzr, when using TypeScript, you should use:

```ts
import swal from 'sweetalert2';
```

Depending on you tsconfig.json strictness, this may throw a warning saying that sweetalert2 has no default export. In that case, use:

```
import * as swal from 'sweetalert2';
```

It's true that SweetAlert2 also defines itself on `window`, but it's better to use it like a module (and that's how it's described in the defintion file).

**Comment by gcaraciolo** [comment]
It could be nice to document this!

**Comment by cmn60** [comment]
> Hello,
> 
> Although it was originally planned, I don't really see the interest of this, since you can just:
> 
> ```ts
> swal({ title: 'Keep things simple :)' });
> ```
> 
> I'm not saying that a service is bad, but the amount of complexity it adds (to the library and userland code) does not seem so worthy (moreover, the goal of this library is also to enforce a declarative approach over an imperative one, and therefore reduce the amount of code in the code-behind).
> 
> However, I'm still open to discussion, and if you can provide a real use case for that I'd be happy to implement such a thing!

Hi;
I'm trying to use an angular component as a swal, and create a service to open/close it.
the idea is to have a common swal that can be used by multiple components. 
is that possible ?

**Comment by kctann** [comment]
@cmn60 Did you find the answer? I am trying this but just cant figure out. : (

**Comment by toverux** [comment]
@kctann it is possible with the library, but then, given your use case, why aren't you just using the sweetalert2 library alone? Or is there some feature of this integration you need?

**Comment by kctann** [comment]
@toverux ,thank you for the quick reply. I am trying to make my alert consistent (after calling API response), so I would like to pop out it with angular's service. I was wondering if we can have a bunch of different style's alert in one component. And when we get response , I can switch to the one to pop out. Or maybe the best way to do this is with the js library for now?
Thank you so much.

**Comment by toverux** [comment]
@kctann It won't be easy as an Angular service can't hold a template. You would need to declare your service, and then have a component that is always loaded by your app (e.g. referenced by your root component), and that component could depend on the service, and register the SwalComponent instances of its template (retrieved in TypeScript via @ViewChild) to the service.

So yeah it's doable but it seems vastly over-engineered for no benefit in your case. I'd recommend you stick with sweetalert2 alone for that.
