### ISSUE TITLE
Is there a way to use a variable instead of a string message?

### ISSUE THREAD

**Issue by diegoarce** [toverux/ngsweetalert2#5]
Hi, I'm trying to use a variable instead of string, is there a way to do that?
in the following example deleteMsg it's a public string variable.

<button class="btn" [swal]="{text: **deleteMsg**, showCancelButton: true, confirmButtonText: 'Yes', cancelButtonText: 'Cancel'}" (confirm)="delete(user)"><i class="fa fa-times"></i></button>

Thanks

**Comment by toverux** [comment]
This is supported by Angular, yes, but `deleteMsg` has to be an instance property.

```
@Component({ ... })
export class MyComponent {
    public deleteMsg = "Delete!";
}
```

(Closing the issue immediately since this is an Angular-specific question.)

**Comment by diegoarce** [comment]
Thanks for your quick answer but my question is regarding the HTML? 
 
I mean,  I agree about your implementation on the component, but what about the html? how can i escape the variable because the variable is not recognized. 

```
@Component({ ... })
export class MyComponent {
    public deleteMsg = "Delete!";
}
```

and 

```
<button class="btn btn-clear" [swal]="{text: deleteMsg,
              showCancelButton: true, confirmButtonText: 'Yes', cancelButtonText: 'Cancel'}"
                      (confirm)="delete(user)">
                <i class="fa fa-times"></i>
              </button>
```

The sweet alert is showed without Text.

**Comment by toverux** [comment]
Strange. Can't test that right now but I don't see what could possibly go bad with a variable.
What your instance variable contains exactly?

**Comment by diegoarce** [comment]
I'm so sorry that was my fault, my apologies. it was an issue on my code. I'm using a translation service  (for multi-language ) and the error was there.
Sorry for make you to spend time on this.  and thank you so much for your help

**Comment by toverux** [comment]
It was likely to be something like that (that's why I've closed the issue so quickly).
No problem, have a good day :)
