### ISSUE TITLE
Allow left / right keys to change focus between buttons

### ISSUE THREAD

**Issue by vipdorian** [toverux/ngsweetalert2#7]
To reproduce:

1. Go to https://limonte.github.io/sweetalert2/
2. Click on "Try me!" below "Ajax request example"
3. Focus on "Submit"
4. By pressing the arrow keys, the focus will change between the buttons. This cannot be achieved with toverux/ngsweetalert2

**Comment by toverux** [comment]
Hi,
That's probably because sweetalert isn't up-to-date. If using yarn, execute `yarn upgrade @toverux/ngsweetalert2`. With npm, delete `node_modules` and run `npm install` (just to be sure, as npm is non-deterministic...). That should work.

**Comment by vipdorian** [comment]
Yes it does work now!
`rm node_modues` and `npm install` did resolve the issue.
Thank you!

**Comment by limonte** [comment]
> https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io/
