### ISSUE TITLE
How can I use html inside alert ?

### ISSUE THREAD

**Issue by MrHOY** [toverux/ngsweetalert2#8]
I don't see how to use html inside alert in README, that mean I can't use html same sweetalert2 js ?

**Comment by toverux** [comment]
Please read the docs closer :)

There are two syntaxes, either the array one where the second index is mapped to `text` (so it doesn't supports HTML, indeed):

```
<button [swal]="['title', 'plain text']"></button>
```

Either the object one:

```html
<button [swal]="{ title: 'title', html: '<b>this is html text</b>' }"></button>
```

That last one takes an object of SweetAlert2 options, so you can pass any options here, including the `html` one.
